### PR TITLE
Review page default applicant

### PR DESCRIPTION
**Pull request by jfrucht25**
Has the review page find an applicant based on the document. If no applicant is found, it uses the label for the document.

### CODE REVIEW

**Comment by shawnchan2014** [comment]
I saw that CI is failing because it cannot find the documents_applicant table. We might need to fix it before merging. Probably it is because we didn't add the newly created migration file in our commit?

**Comment by jfrucht25** [comment]
> I saw that CI is failing because it cannot find the documents_applicant table. We might need to fix it before merging. Probably it is because we didn't add the newly created migration file in our commit?

This other pr fixes it https://github.com/CMU-313/fall-2021-hw2-connect5/pull/31, so merge both and we should be good

**Comment by jfrucht25** [comment]
Resolves #26

**Review by gramliu — APPROVED** [review]
Looks good to me

**Pull request merged**
